--------------------------------
---------- 시퀀스 삭제 -----------
--------------------------------
DROP SEQUENCE SEQ_MEMBER_NO;
DROP SEQUENCE SEQ_BOOSTER_PROD_NO;
DROP SEQUENCE SEQ_BOOSTER_REVIEW_NO;
DROP SEQUENCE SEQ_NORMAL_PROD_NO;
DROP SEQUENCE SEQ_NORMAL_REVIEW_NO;
DROP SEQUENCE SEQ_FOOD_PROD_NO;
DROP SEQUENCE SEQ_FOOD_REVIEW_NO;
DROP SEQUENCE SEQ_ANNOUNCEMENT_BOARD_NO;
DROP SEQUENCE SEQ_BOARD_NO;



--------------------------------
---------- 시퀀스 생성 -----------
--------------------------------
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOOSTER_PROD_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOOSTER_REVIEW_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NORMAL_PROD_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_NORMAL_REVIEW_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FOOD_PROD_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FOOD_REVIEW_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ANNOUNCEMENT_BOARD_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE NOCYCLE;


--------------------------------
---------- 테이블 삭제 -----------
--------------------------------
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE BOOSTER_PRODUCT cascade constraints;
DROP TABLE BOOSTER_REVIEW cascade constraints;
DROP TABLE NORMAL_PRODUCT CASCADE CONSTRAINTS;
DROP TABLE NORMAL_REVIEW CASCADE CONSTRAINTS;
DROP TABLE FOOD_PRODUCT cascade constraints;
DROP TABLE FOOD_REVIEW cascade constraints;
DROP TABLE ANNOUNCEMENT_BOARD CASCADE CONSTRAINTS;
DROP TABLE ANNOUNCEMENT_BAORD CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;



--------------------------------
---------- 테이블 생성 -----------
--------------------------------
CREATE TABLE MEMBER(
    NO                      NUMBER          CONSTRAINT PK_MEMBER_NO PRIMARY KEY
    , ID                    VARCHAR2(100)   CONSTRAINT NN_MEMBER_ID NOT NULL CONSTRAINT UQ_MEMBER_ID UNIQUE
    , PWD                   VARCHAR2(100)   CONSTRAINT NN_MEMBER_PWD NOT NULL
    , NICK                  VARCHAR2(100)   CONSTRAINT NN_MEMBER_NICK NOT NULL --?슦由? ?궗?씠?듃?뒗 ?땳?꽕?엫 以묐났?? ?뿀?슜?븷嫄곗엫
    , JOIN_DATE             TIMESTAMP       DEFAULT SYSDATE
    , MODIFY_DATE           TIMESTAMP       
    , QUIT_YN               CHAR(1)         DEFAULT 'N' CONSTRAINT CK_MEMBER_QUIT CHECK( QUIT_YN IN ('Y','N')  )
    , ADMIN_YN              CHAR(1)         DEFAULT 'N' CONSTRAINT CK_MEMBER_ISADMIN CHECK( ADMIN_YN IN ('Y','N')  )
);

CREATE TABLE BOOSTER_PRODUCT (
   BOOSTER_PROD_NO           NUMBER         PRIMARY KEY,
   NAME                      VARCHAR2(100)  NOT NULL,
   PRICE                     NUMBER,
   IS_DISCOUNTINUED_YN       CHAR(1)        DEFAULT 'N' CONSTRAINT CK_DIS_YN_1 CHECK (IS_DISCOUNTINUED_YN IN ('Y','N')),
   DESCRIPTION               VARCHAR2(1000)      
);

CREATE TABLE BOOSTER_REVIEW (
   BOOSTER_REVIEW_NO         NUMBER         PRIMARY KEY,
   REVIEW_TITLE              VARCHAR2(100),
   REVIEW                    VARCHAR2(1000) NULL,
   BOOSTER_PROD_NO           NUMBER,
   MEMBER_NO                 NUMBER,
   ENROLL_DATE               timestamp      DEFAULT SYSDATE,
   QUIT_YN                   CHAR(1)        DEFAULT 'N' CONSTRAINT CK_QUIT_YN_1 CHECK( QUIT_YN IN ('Y','N'))      
);

CREATE TABLE NORMAL_PRODUCT (
   NORMAL_PROD_NO           NUMBER          PRIMARY KEY,
   NAME                     VARCHAR2(100)   NOT NULL,
   PRICE                    NUMBER,
   IS_DISCOUNTINUED_YN      CHAR(1)         DEFAULT 'N' CONSTRAINT CK_DIS_YN_2 CHECK (IS_DISCOUNTINUED_YN IN ('Y','N')),
   DESCRIPTION              VARCHAR2(1000)       
);

CREATE TABLE NORMAL_REVIEW (
   NORMAL_REVIEW_NO         NUMBER          PRIMARY KEY,
   REVIEW_TITLE             VARCHAR2(100),
   REVIEW                   VARCHAR2(1000)  NULL,
   NORMAL_PROD_NO           NUMBER,
   WRITER_NO                NUMBER,
   ENROLL_DATE              TIMESTAMP       DEFAULT SYSDATE,
   QUIT_YN                  CHAR(1)         DEFAULT 'N'CONSTRAINT CK_QUIT_YN_2 CHECK( QUIT_YN IN ('Y','N') )
);

CREATE TABLE FOOD_PRODUCT (
	FOOD_PROD_NO	        NUMBER          PRIMARY KEY ,
	NAME	                VARCHAR2(1000)  NOT NULL,
	PRICE	                NUMBER		    ,
	IS_DISCOUNTINUED_YN	    CHAR(1)		    DEFAULT 'N' CONSTRAINT CK_DIS_YN_3 CHECK (IS_DISCOUNTINUED_YN IN ('Y','N')),
	DESCRIPTION	            VARCHAR2(1000)	    
);

CREATE TABLE FOOD_REVIEW (
	FOOD_REVIEW_NO	        NUMBER          PRIMARY KEY,
    REVIEW_TITLE            VARCHAR2(100),
	REVIEW	                VARCHAR2(1000)	NULL,
	FOOD_PROD_NO	        NUMBER,
	WRITER_NO	            NUMBER	,
	ENROLL_DATE	            timestamp       DEFAULT SYSDATE,
	QUIT_YN	                char(1)	        DEFAULT 'N'CONSTRAINT CK_QUIT_YN_3 CHECK( QUIT_YN IN ('Y','N') )
);

CREATE TABLE ANNOUNCEMENT_BOARD (
    NO                  NUMBER              PRIMARY KEY
    , TITLE             VARCHAR2(1000)      CONSTRAINT NN_ANNOUNCEMENT_BOARD_TITLE NOT NULL
    , CONTENT           VARCHAR2(4000)      CONSTRAINT NN_ANNOUNCEMENT_BOARD_CONTENT NOT NULL
    , WRITER_NO         NUMBER
    , ENROLL_DATE       TIMESTAMP           DEFAULT SYSDATE
    , DEL_YN            CHAR(1)             DEFAULT 'N' CONSTRAINT CK_ANNOUNCEMENT_BOARD_DEL CHECK(DEL_YN IN ('Y','N'))
);

CREATE TABLE BOARD (
    NO                  NUMBER          PRIMARY KEY
    , TITLE             VARCHAR2(1000)  CONSTRAINT NN_BOARD_TITLE NOT NULL
    , CONTENT           VARCHAR2(4000)  CONSTRAINT NN_BOARD_CONTENT NOT NULL
    , WRITER_NO         NUMBER
    , ENROLL_DATE       TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN            CHAR(1)         DEFAULT 'N' CONSTRAINT CK_BAORD_DEL CHECK(DEL_YN IN ('Y','N'))
);




--------------------------------
---------- 외래키 설정 -----------
--------------------------------

ALTER TABLE BOOSTER_REVIEW
ADD CONSTRAINT FK_BOOSTER_PROD_NO FOREIGN KEY (BOOSTER_PROD_NO) REFERENCES BOOSTER_PRODUCT(BOOSTER_PROD_NO);

ALTER TABLE BOOSTER_REVIEW
ADD CONSTRAINT FK_BR_MEMBERNO FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(NO);

ALTER TABLE NORMAL_REVIEW 
ADD CONSTRAINT FK_NORMAL_PROD_NO FOREIGN KEY (NORMAL_PROD_NO) REFERENCES NORMAL_PRODUCT(NORMAL_PROD_NO);

ALTER TABLE NORMAL_REVIEW
ADD CONSTRAINT FK_NORMAL_MEMBER_NO FOREIGN KEY (WRITER_NO) REFERENCES MEMBER(NO);

ALTER TABLE FOOD_REVIEW 
ADD CONSTRAINT FK_FOOD_PROD_NO FOREIGN KEY (FOOD_PROD_NO) REFERENCES FOOD_PRODUCT(FOOD_PROD_NO);

ALTER TABLE FOOD_REVIEW
ADD CONSTRAINT FK_FOOD_MEMBER_NO FOREIGN KEY (WRITER_NO) REFERENCES MEMBER(NO);

ALTER TABLE BOARD 
ADD CONSTRAINT FK_MEMBER_TO_BOARD_NO FOREIGN KEY (WRITER_NO)REFERENCES MEMBER (NO);


ALTER TABLE ANNOUNCEMENT_BOARD 
ADD CONSTRAINT FK_MEMBER_TO_ANNOUNCEMENT_BOARD_NO FOREIGN KEY (WRITER_NO)REFERENCES MEMBER (NO);


--------------------------------
---------- 더미데이터 생성 -----------
--------------------------------

------------- 아이디 추가 -------------
INSERT INTO MEMBER(NO, ID, PWD, NICK, ADMIN_YN) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'admin', '1234', '관리자', 'Y'); -- 愿?由ъ옄怨꾩젙 ?궫?엯
INSERT INTO MEMBER(NO, ID, PWD, NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'nyamnyam', '1234', 'nyamgu'); 
INSERT INTO MEMBER(NO, ID, PWD, NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'gugu', '1234', 'gugu'); 
INSERT INTO MEMBER(NO, ID, PWD, NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user03', '1234', 'nick03'); 
INSERT INTO MEMBER(NO, ID, PWD, NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user04', '1234', 'nicknick'); 
INSERT INTO MEMBER(NO, ID, PWD, NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user05', 'password', 'nicksix'); 
INSERT INTO MEMBER(NO, ID, PWD, NICK) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'hoho', '1234', 'hehe'); 

------------- 음식 물품 추가 -------------
INSERT INTO FOOD_PRODUCT(FOOD_PROD_NO, NAME, PRICE, DESCRIPTION) VALUES(SEQ_FOOD_PROD_NO.NEXTVAL, '프리미엄 닭가슴살', '2000', '5성급 셰프가 직접 만들어 좋은 품질');
INSERT INTO FOOD_PRODUCT(FOOD_PROD_NO, NAME, PRICE, DESCRIPTION) VALUES(SEQ_FOOD_PROD_NO.NEXTVAL, '닭가슴살 도시락', '9000', '탄수화물 51g 단백질 39g 지방6g 다이어트 할때 한끼로 먹기 좋은 제품');
INSERT INTO FOOD_PRODUCT(FOOD_PROD_NO, NAME, PRICE, DESCRIPTION) VALUES(SEQ_FOOD_PROD_NO.NEXTVAL, '닭가슴살 든든밥바 야체', '1700', '국내산 닭가슴살과 밴런스 잡힌 영양소 속높은 활용도');
INSERT INTO FOOD_PRODUCT(FOOD_PROD_NO, NAME, PRICE, DESCRIPTION) VALUES(SEQ_FOOD_PROD_NO.NEXTVAL, '다이어트 한식 도시락', '16000', '체중조절용 다이어트 도시락 반찬까지 다 먹어도 360Kcal');
INSERT INTO FOOD_PRODUCT(FOOD_PROD_NO, NAME, PRICE, DESCRIPTION) VALUES(SEQ_FOOD_PROD_NO.NEXTVAL, '새우볶음밥AND동그랑땡', '21900', '새우와 각종 채소가 많이 들어있어 균형적인 영양소 섭취 가능');
INSERT INTO FOOD_PRODUCT(FOOD_PROD_NO, NAME, PRICE, DESCRIPTION) VALUES(SEQ_FOOD_PROD_NO.NEXTVAL, '소고기볼 오리지널', '27000', '부드러운 호주산 소고기를 사용 간편하게 먹을 수 있는 한입 크기');
INSERT INTO FOOD_PRODUCT(FOOD_PROD_NO, NAME, PRICE, DESCRIPTION) VALUES(SEQ_FOOD_PROD_NO.NEXTVAL, '소고기 청양고추 스테이크', '29000', '맛있게 맵고 물리지 않게 먹을수 있는 스테이크');
INSERT INTO FOOD_PRODUCT(FOOD_PROD_NO, NAME, PRICE, DESCRIPTION) VALUES(SEQ_FOOD_PROD_NO.NEXTVAL, '견과류 세트', '45000', '우리에게 필요한 5가지 종류의 신선한 견과류 사용');
INSERT INTO FOOD_PRODUCT(FOOD_PROD_NO, NAME, PRICE, DESCRIPTION) VALUES(SEQ_FOOD_PROD_NO.NEXTVAL, '풀업 샐러드 너트AND리코타', '23700','푸짐한 양과 퀄리티를 둘다 잡아 샐러드 전문점 못지 않는 제품');
INSERT INTO FOOD_PRODUCT(FOOD_PROD_NO, NAME, PRICE, DESCRIPTION) VALUES(SEQ_FOOD_PROD_NO.NEXTVAL, '이지 샐러드 AYPE', '11900', '세척과 손질이 되어 바로 먹어도 OK 파우치 포장으로 어디서든지 먹기좋은 제품');
INSERT INTO FOOD_PRODUCT(FOOD_PROD_NO, NAME, PRICE, DESCRIPTION) VALUES(SEQ_FOOD_PROD_NO.NEXTVAL, 'DAILY 샐러드 그린100g', '2100', '국내산 채소를 사용 원하는 토핑과 소스로 나만의 샐러드 만들기 가능');
INSERT INTO FOOD_PRODUCT(FOOD_PROD_NO, NAME, PRICE, DESCRIPTION) VALUES(SEQ_FOOD_PROD_NO.NEXTVAL, '에어치킨 한입 닭다리살', '6000', '오븐에 구워 기름기 빼고 에어프라이기로 간편하게 국내산 우리 닭');
INSERT INTO FOOD_PRODUCT(FOOD_PROD_NO, NAME, PRICE, DESCRIPTION) VALUES(SEQ_FOOD_PROD_NO.NEXTVAL, '아이스 군 고구마 호박 고구마', '11900', '찐~한 색감과 쫀득~한 호박같은 맛!');
INSERT INTO FOOD_PRODUCT(FOOD_PROD_NO, NAME, PRICE, DESCRIPTION) VALUES(SEQ_FOOD_PROD_NO.NEXTVAL, '치즈품은 고구마', '4900', '고구마 ♥ 치즈의 환상 케미');
INSERT INTO FOOD_PRODUCT(FOOD_PROD_NO, NAME, PRICE, DESCRIPTION) VALUES(SEQ_FOOD_PROD_NO.NEXTVAL, '알뜰곤약면 물냉면', '3000', '헹굼없이 바로 먹는 곤약면 냄새가 없는 곤약면 60Kcal 가벼운 곤약면');


------------- 음식 리뷰 추가 -------------
INSERT INTO FOOD_REVIEW(FOOD_REVIEW_NO, REVIEW_TITLE, REVIEW, FOOD_PROD_NO, WRITER_NO, ENROLL_DATE) VALUES(SEQ_FOOD_REVIEW_NO.NEXTVAL, '한식 도시락 리뷰', 'ㄹㅇ 한끼 든든하게 먹고 싶으면 추천드립니다. 정말 맛있엇요!!', 4, 3,SYSDATE);
INSERT INTO FOOD_REVIEW(FOOD_REVIEW_NO, REVIEW_TITLE, REVIEW, FOOD_PROD_NO, WRITER_NO, ENROLL_DATE) VALUES(SEQ_FOOD_REVIEW_NO.NEXTVAL, '닭가슴살 도시락', '일반 도시락 보다 먹기 좋아요!!! 다음에 또 시킬 정도로 추천 드립니다!!!', 2, 4,SYSDATE);
INSERT INTO FOOD_REVIEW(FOOD_REVIEW_NO, REVIEW_TITLE, REVIEW, FOOD_PROD_NO, WRITER_NO, ENROLL_DATE) VALUES(SEQ_FOOD_REVIEW_NO.NEXTVAL, '추천 할 만한 샐러드!!', '체중 유지 하려고 요즘 샐러드 먹고 있는데 정말 좋아요 매일 먹어도 물리지 않는 샐러드에요!!!', 9, 2,SYSDATE);
INSERT INTO FOOD_REVIEW(FOOD_REVIEW_NO, REVIEW_TITLE, REVIEW, FOOD_PROD_NO, WRITER_NO, ENROLL_DATE) VALUES(SEQ_FOOD_REVIEW_NO.NEXTVAL, '맛좋은 고구마~~~', '고구마 별로 안좋아하는데 이 고구마는 정말 맛있어요!!!!', 14, 5,SYSDATE);
INSERT INTO FOOD_REVIEW(FOOD_REVIEW_NO, REVIEW_TITLE, REVIEW, FOOD_PROD_NO, WRITER_NO, ENROLL_DATE) VALUES(SEQ_FOOD_REVIEW_NO.NEXTVAL, '선물 하기 좋은 견과류^^', '운동하는 친구들에게 선물하기 좋아요 양도 많고 포장이 잘되어 있어 좋습니다', 8, 6,SYSDATE);
INSERT INTO FOOD_REVIEW(FOOD_REVIEW_NO, REVIEW_TITLE, REVIEW, FOOD_PROD_NO, WRITER_NO, ENROLL_DATE) VALUES(SEQ_FOOD_REVIEW_NO.NEXTVAL, '간식으로 먹기 좋은 음식', '간식으로 먹기가 좋아서 종종 사먹습니다~ 닭가슴살이 지겨우면 한번쯤 먹기 좋아요', 12, 5,SYSDATE);
INSERT INTO FOOD_REVIEW(FOOD_REVIEW_NO, REVIEW_TITLE, REVIEW, FOOD_PROD_NO, WRITER_NO, ENROLL_DATE) VALUES(SEQ_FOOD_REVIEW_NO.NEXTVAL, '이거 별로임..... 비추..', '물냉면 먹고 싶어서 먹어봤는데 곤약 특유 냄새가 많이 나서 먹기 힘들었어요ㅠㅠ', 15, 2,SYSDATE);
INSERT INTO FOOD_REVIEW(FOOD_REVIEW_NO, REVIEW_TITLE, REVIEW, FOOD_PROD_NO, WRITER_NO, ENROLL_DATE) VALUES(SEQ_FOOD_REVIEW_NO.NEXTVAL, '닭이 지겨우면 이거 먹어봐요^^', '닭고기사 너무 지겨워서 시켜봤는데 정말 좋아요 가끔씩 먹으면 좋을꺼 같아요 하지만 좀 비싸서 이벤트할때 사면 좋을꺼 같아요', 7, 4,SYSDATE);
INSERT INTO FOOD_REVIEW(FOOD_REVIEW_NO, REVIEW_TITLE, REVIEW, FOOD_PROD_NO, WRITER_NO, ENROLL_DATE) VALUES(SEQ_FOOD_REVIEW_NO.NEXTVAL, '맛있는 볶음밥 찾음!!!!!!', '진짜 맨날 다이어트 도시락만 먹다가 이번에 볶음밥있어 먹어봤는데 정말 맛있어요!! 다이어트 도시락 지겨우면 한번씩 먹어야겠어요', 5, 7,SYSDATE);
INSERT INTO FOOD_REVIEW(FOOD_REVIEW_NO, REVIEW_TITLE, REVIEW, FOOD_PROD_NO, WRITER_NO, ENROLL_DATE) VALUES(SEQ_FOOD_REVIEW_NO.NEXTVAL, '간편하게 먹을 만한 한끼 식사 대용', '아침에 출근하기전 밥먹기 힘들때 하나 챙겨가서 먹기 좋아요 생각보다 든든하고 좋아요', 3, 6,SYSDATE);
INSERT INTO FOOD_REVIEW(FOOD_REVIEW_NO, REVIEW_TITLE, REVIEW, FOOD_PROD_NO, WRITER_NO, ENROLL_DATE) VALUES(SEQ_FOOD_REVIEW_NO.NEXTVAL, '운동후 먹기좋은 닭가슴살', '퍽퍽한 닭가슴살이 아닌 촉촉하고 먹기 좋은 닭가슴살이에요 저 이거먹고 5KG 뺐어요!!', 1, 3,SYSDATE);
INSERT INTO FOOD_REVIEW(FOOD_REVIEW_NO, REVIEW_TITLE, REVIEW, FOOD_PROD_NO, WRITER_NO, ENROLL_DATE) VALUES(SEQ_FOOD_REVIEW_NO.NEXTVAL, '소고기 먹고 싶을때 간식으로 추천@@@@', '한입 크기여서 간식으로 먹기 좋아요 그리고 생각보다 소고기 식감이 많이 나서 진짜 소먹는 기분이에요~~~!!', 6, 4,SYSDATE);
INSERT INTO FOOD_REVIEW(FOOD_REVIEW_NO, REVIEW_TITLE, REVIEW, FOOD_PROD_NO, WRITER_NO, ENROLL_DATE) VALUES(SEQ_FOOD_REVIEW_NO.NEXTVAL, '볶음밥 생각보다 별로....', '윗글보고 먹어봤는데 제입맛에서는 별로..... 그레도 동그랑땡은 맛있었음ㅎㅎ', 5, 6,SYSDATE);
INSERT INTO FOOD_REVIEW(FOOD_REVIEW_NO, REVIEW_TITLE, REVIEW, FOOD_PROD_NO, WRITER_NO, ENROLL_DATE) VALUES(SEQ_FOOD_REVIEW_NO.NEXTVAL, '윗글보다 맛있는 고구마 찾음!!', '비싸긴한데 생각보다 엄참 맛있음!! 호박 고구마 좋아하면 이거 시켜 먹어봐요', 13, 2,SYSDATE);
INSERT INTO FOOD_REVIEW(FOOD_REVIEW_NO, REVIEW_TITLE, REVIEW, FOOD_PROD_NO, WRITER_NO, ENROLL_DATE) VALUES(SEQ_FOOD_REVIEW_NO.NEXTVAL, '채소 사기 힘들때 먹을만한 샐러드', '채소사서 매일 소분하기 힘든데 이거 사고 먹기 그런 귀찮은 일이 없어서 좋아요 소분 귀찮으면 진짜 엄청 추천!!!!!', 10, 7,SYSDATE);


------------- BOOSTER 상품 추가 -------------
INSERT INTO BOOSTER_PRODUCT (BOOSTER_PROD_NO, NAME, PRICE, IS_DISCOUNTINUED_YN, DESCRIPTION)
VALUES (SEQ_BOOSTER_PROD_NO.NEXTVAL, 'EVLution Nutrition, ENGN, Pre-workout Engine, 블루 라즈베리 맛, 312g(11oz)', 27952, 'N', '규칙적인 운동과 병행하며 ENGN® Pre-Workout 보충제를 복용하면 다음 측면에서 효과를 볼 수 있습니다. 집중력, 에너지, 운동능력');
INSERT INTO BOOSTER_PRODUCT (BOOSTER_PROD_NO, NAME, PRICE, IS_DISCOUNTINUED_YN, DESCRIPTION)
VALUES (SEQ_BOOSTER_PROD_NO.NEXTVAL, '비에스엔 신타6단백질파우더 쿠키앤크림맛 28회분', 34900, 'N', '세상 맛있는 국민 단백질, 신타6-쿠키앤크림맛');
INSERT INTO BOOSTER_PRODUCT (BOOSTER_PROD_NO, NAME, PRICE, IS_DISCOUNTINUED_YN, DESCRIPTION)
VALUES (SEQ_BOOSTER_PROD_NO.NEXTVAL, 'JNX Sports, The Curse, 운동 전 보충제, 체리 라임에이드 맛, 150g(5.3oz)', 24104, 'N', 'The Curse!®의 초자연적인 힘으로 신체의 진정한 잠재력을 끌어내십시오.');
INSERT INTO BOOSTER_PRODUCT (BOOSTER_PROD_NO, NAME, PRICE, IS_DISCOUNTINUED_YN, DESCRIPTION)
VALUES (SEQ_BOOSTER_PROD_NO.NEXTVAL, '삼대오백 헬스부스터', 19900, 'N', '운동 시작부터 끝까지 강력한 펌핑감을 느낄수 있도록 돕는 강력한 헬스 부스터입니다.');
INSERT INTO BOOSTER_PRODUCT (BOOSTER_PROD_NO, NAME, PRICE, IS_DISCOUNTINUED_YN, DESCRIPTION)
VALUES (SEQ_BOOSTER_PROD_NO.NEXTVAL, '익스트림 OPTIMA BCAA 타우린 7000+', 20865, 'N', '9중 필수 아미노산 충전 완료!');
INSERT INTO BOOSTER_PRODUCT (BOOSTER_PROD_NO, NAME, PRICE, IS_DISCOUNTINUED_YN, DESCRIPTION)
VALUES (SEQ_BOOSTER_PROD_NO.NEXTVAL, '익스트림 트리플 아르기닌 6200', 18315, 'N', '4중에너지 싸이클 흡수율 UP 시너지 2배');
INSERT INTO BOOSTER_PRODUCT (BOOSTER_PROD_NO, NAME, PRICE, IS_DISCOUNTINUED_YN, DESCRIPTION)
VALUES (SEQ_BOOSTER_PROD_NO.NEXTVAL, '익스트림 아르기닌 젤리스틱', 18315, 'N', '고단백 10g 함유 LOW SUGAR');
INSERT INTO BOOSTER_PRODUCT (BOOSTER_PROD_NO, NAME, PRICE, IS_DISCOUNTINUED_YN, DESCRIPTION)
VALUES (SEQ_BOOSTER_PROD_NO.NEXTVAL, '익스트림 듀얼 아르기닌 플러스', 18315, 'N', '활력 특허 성분 바이오페린 함유');
INSERT INTO BOOSTER_PRODUCT (BOOSTER_PROD_NO, NAME, PRICE, IS_DISCOUNTINUED_YN, DESCRIPTION)
VALUES (SEQ_BOOSTER_PROD_NO.NEXTVAL, '익스트림 글루타민 ZMA', 18315, 'N', '글루타민 + ZMA 자신있게 선보이는 배합');
INSERT INTO BOOSTER_PRODUCT (BOOSTER_PROD_NO, NAME, PRICE, IS_DISCOUNTINUED_YN, DESCRIPTION)
VALUES (SEQ_BOOSTER_PROD_NO.NEXTVAL, '셀루코어 C4 오리지널 프리워크아웃 그린애플맛', 41560, 'N', '운동 전 섭취하는 식이 보충제');
INSERT INTO BOOSTER_PRODUCT (BOOSTER_PROD_NO, NAME, PRICE, IS_DISCOUNTINUED_YN, DESCRIPTION)
VALUES (SEQ_BOOSTER_PROD_NO.NEXTVAL, '셀루코어 C4 오리지널 프리워크아웃 프루트 펀치 맛', 41560, 'N', '운동 전 섭취하는 식이 보충제');
INSERT INTO BOOSTER_PRODUCT (BOOSTER_PROD_NO, NAME, PRICE, IS_DISCOUNTINUED_YN, DESCRIPTION)
VALUES (SEQ_BOOSTER_PROD_NO.NEXTVAL, '잠백이 펌프 무카페인 아르기닌 헬스부스터 70ml 30팩', 39500, 'N', '6000mg의 아낌없는 고함량 아르기닌');
INSERT INTO BOOSTER_PRODUCT (BOOSTER_PROD_NO, NAME, PRICE, IS_DISCOUNTINUED_YN, DESCRIPTION)
VALUES (SEQ_BOOSTER_PROD_NO.NEXTVAL, '뉴트리디데이 L 아르기닌, 120정, 2개', 22710, 'N', '바쁜 당신을 위한 나만의 잇템!');
INSERT INTO BOOSTER_PRODUCT (BOOSTER_PROD_NO, NAME, PRICE, IS_DISCOUNTINUED_YN, DESCRIPTION)
VALUES (SEQ_BOOSTER_PROD_NO.NEXTVAL, 'EVLUTIONNUTRITION 웨이 프로틴 더블 리치 초콜릿 맛', 47100, 'N', '고품질의 분리 유청 단백질 파우더입니다.');
INSERT INTO BOOSTER_PRODUCT (BOOSTER_PROD_NO, NAME, PRICE, IS_DISCOUNTINUED_YN, DESCRIPTION)
VALUES (SEQ_BOOSTER_PROD_NO.NEXTVAL, 'EVLUTIONNUTRITION 웨이 프로틴 딸기맛', 47100, 'N', '고품질의 분리 유청 단백질 파우더입니다.');



------------- BOOSTER 리뷰 추가 -------------
INSERT INTO BOOSTER_REVIEW (BOOSTER_REVIEW_NO, REVIEW_TITLE,
REVIEW, BOOSTER_PROD_NO, MEMBER_NO, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_BOOSTER_REVIEW_NO.NEXTVAL, '좋음', '일단 맛이 좋아요 그리구 성분적인 면에서 고품질이기 때문에 가격이 좀 쎈편이어도 운동전에 챙겨먹고 있어요.', SEQ_BOOSTER_PROD_NO.CURRVAL, 2,
SYSDATE, 'N');
INSERT INTO BOOSTER_PRODUCT (BOOSTER_PROD_NO, NAME, PRICE, IS_DISCOUNTINUED_YN, DESCRIPTION)
VALUES (SEQ_BOOSTER_PROD_NO.NEXTVAL, '비에스엔 신타6단백질파우더 쿠키앤크림맛 28회분', 34900, 'N', '세상 맛있는 국민 단백질, 신타6-쿠키앤크림맛');
INSERT INTO BOOSTER_REVIEW (BOOSTER_REVIEW_NO, REVIEW_TITLE,
REVIEW, BOOSTER_PROD_NO, MEMBER_NO, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_BOOSTER_REVIEW_NO.NEXTVAL, '예상보다 맛있어요', '신타6은 훌륭한 단백질공급원입니다.', SEQ_BOOSTER_PROD_NO.CURRVAL, 3,
SYSDATE, 'N');
INSERT INTO BOOSTER_REVIEW (BOOSTER_REVIEW_NO, REVIEW_TITLE,
REVIEW, BOOSTER_PROD_NO, MEMBER_NO, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_BOOSTER_REVIEW_NO.NEXTVAL, '아침 운동에 좋습니다.', '아침 운동을 준비했어요. 체리맛 맛이 좋아요. 품질은 제가 필요로 하는 것에 완벽합니다. 다시 살 것입니다. 나는 매일 아침 그것을 나의 일과로 삼는다.', SEQ_BOOSTER_PROD_NO.CURRVAL, 4,
SYSDATE, 'N');
INSERT INTO BOOSTER_REVIEW (BOOSTER_REVIEW_NO, REVIEW_TITLE,
REVIEW, BOOSTER_PROD_NO, MEMBER_NO, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_BOOSTER_REVIEW_NO.NEXTVAL, '좋아요.', '좋아요.', SEQ_BOOSTER_PROD_NO.CURRVAL, 5,
SYSDATE, 'N');
INSERT INTO BOOSTER_REVIEW (BOOSTER_REVIEW_NO, REVIEW_TITLE,
REVIEW, BOOSTER_PROD_NO, MEMBER_NO, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_BOOSTER_REVIEW_NO.NEXTVAL, '빠른 배송 감사합니다.', '배송이 빨라서 좋아요.', SEQ_BOOSTER_PROD_NO.CURRVAL, 6,
SYSDATE, 'N');
INSERT INTO BOOSTER_REVIEW (BOOSTER_REVIEW_NO, REVIEW_TITLE,
REVIEW, BOOSTER_PROD_NO, MEMBER_NO, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_BOOSTER_REVIEW_NO.NEXTVAL, '좋아요', '신랑이 꾸준히 복용중입니다. 좋으니까 먹겠지요?', SEQ_BOOSTER_PROD_NO.CURRVAL, 3,
SYSDATE, 'N');
INSERT INTO BOOSTER_REVIEW (BOOSTER_REVIEW_NO, REVIEW_TITLE,
REVIEW, BOOSTER_PROD_NO, MEMBER_NO, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_BOOSTER_REVIEW_NO.NEXTVAL, '득근', '기존 먹던 제품보다도 함량이 높은걸 찾고 있었는데 딱입니다.', SEQ_BOOSTER_PROD_NO.CURRVAL, 2,
SYSDATE, 'N');
INSERT INTO BOOSTER_REVIEW (BOOSTER_REVIEW_NO, REVIEW_TITLE,
REVIEW, BOOSTER_PROD_NO, MEMBER_NO, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_BOOSTER_REVIEW_NO.NEXTVAL, '이거 없으면 안돼', '이제 이거 없으면 운동을 못합니다. 운동하시는분들 강추!', SEQ_BOOSTER_PROD_NO.CURRVAL, 4,
SYSDATE, 'N');
INSERT INTO BOOSTER_REVIEW (BOOSTER_REVIEW_NO, REVIEW_TITLE,
REVIEW, BOOSTER_PROD_NO, MEMBER_NO, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_BOOSTER_REVIEW_NO.NEXTVAL, '정제 제품', '매번 가루 형태로 글루타민을 섭취 하였는데 정제 제품 찾던중 구매 했습니다.', SEQ_BOOSTER_PROD_NO.CURRVAL, 3,
SYSDATE, 'N');
INSERT INTO BOOSTER_REVIEW (BOOSTER_REVIEW_NO, REVIEW_TITLE,
REVIEW, BOOSTER_PROD_NO, MEMBER_NO, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_BOOSTER_REVIEW_NO.NEXTVAL, '추천합니다', '현역 스포츠 트레이너입니다. 셀루코어는 거의 모든 맛을 먹어봤는데 개인적으로 이 맛이 신선하고 좋아요', SEQ_BOOSTER_PROD_NO.CURRVAL, 5,
SYSDATE, 'N');
INSERT INTO BOOSTER_REVIEW (BOOSTER_REVIEW_NO, REVIEW_TITLE,
REVIEW, BOOSTER_PROD_NO, MEMBER_NO, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_BOOSTER_REVIEW_NO.NEXTVAL, '너무 좋습니다', '운동할 때의 효과도 효과지만 밤에 잠을 못 잘 정도로 강력합니다.', SEQ_BOOSTER_PROD_NO.CURRVAL, 4,
SYSDATE, 'N');
INSERT INTO BOOSTER_REVIEW (BOOSTER_REVIEW_NO, REVIEW_TITLE,
REVIEW, BOOSTER_PROD_NO, MEMBER_NO, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_BOOSTER_REVIEW_NO.NEXTVAL, '먹기 불편해요', '칠칠이들은 못 먹겠어요 ㅜ 먹다 옷에 다 쏟음ㅠ', SEQ_BOOSTER_PROD_NO.CURRVAL, 3,
SYSDATE, 'N');
INSERT INTO BOOSTER_REVIEW (BOOSTER_REVIEW_NO, REVIEW_TITLE,
REVIEW, BOOSTER_PROD_NO, MEMBER_NO, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_BOOSTER_REVIEW_NO.NEXTVAL, '적당히 만족해요', '리뷰 보고 구입했는데 남편이 체력도 떨어지고 피곤해서 구입했어요.', SEQ_BOOSTER_PROD_NO.CURRVAL, 4,
SYSDATE, 'N');
INSERT INTO BOOSTER_REVIEW (BOOSTER_REVIEW_NO, REVIEW_TITLE,
REVIEW, BOOSTER_PROD_NO, MEMBER_NO, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_BOOSTER_REVIEW_NO.NEXTVAL, '추천해요', '가루가 물에 잘 풀리고 맛도 좋고 여드름이 난다거나 하지도 않습니다.', SEQ_BOOSTER_PROD_NO.CURRVAL, 2,
SYSDATE, 'N');
INSERT INTO BOOSTER_REVIEW (BOOSTER_REVIEW_NO, REVIEW_TITLE,
REVIEW, BOOSTER_PROD_NO, MEMBER_NO, ENROLL_DATE, QUIT_YN)
VALUES (SEQ_BOOSTER_REVIEW_NO.NEXTVAL, '엄청 달고 좋아요.', '오래 먹으면 느끼하거나 물리는 감이 있을 법 한데 무난하게 좋음.', SEQ_BOOSTER_PROD_NO.CURRVAL, 6,
SYSDATE, 'N');

------------- 공지사항 추가 -------------
INSERT INTO ANNOUNCEMENT_BOARD(NO, TITLE, CONTENT, WRITER_NO) VALUES(SEQ_ANNOUNCEMENT_BOARD_NO.NEXTVAL , '게시판 이용 규칙 안내.' , '회원 여러분들은 게시판 내에서 서로 예의를 갖추고 존중하는 분위기를 조성해 주시기 바랍니다.' || CHR(10) || '     과도한 욕설 사용 시 이용 제한 조치 될 수 있으니 참고하시기 바랍니다.' || CHR(10) || '  감사합니다.', '1');
INSERT INTO ANNOUNCEMENT_BOARD(NO, TITLE, CONTENT, WRITER_NO) VALUES(SEQ_ANNOUNCEMENT_BOARD_NO.NEXTVAL , '서비스 점검 공지.' , '더욱 더 나은 서비스를 위해 서버 점검을 진행할 예정입니다.' || CHR(10) || '     오전6시 ~ 9시 사이 사이트 이용이 어렵습니다.(시간은 상황에 따라 연장 될 수 있습니다.)' || CHR(10) || '  감사합니다.', '1');
INSERT INTO ANNOUNCEMENT_BOARD(NO, TITLE, CONTENT, WRITER_NO) VALUES(SEQ_ANNOUNCEMENT_BOARD_NO.NEXTVAL , '버그 신고 및 피드백 제공' , '서비스 이용간에 버그나 문제가 발생할 시 가능한 빠르게 관리자에게 신고해주시기를 부탁드립니다.' || CHR(10) || '     또한 피드백이나 제안이 있으시면 공유해시면 감사하겠습니다.' || CHR(10) || '  감사합니다.', '1');
INSERT INTO ANNOUNCEMENT_BOARD(NO, TITLE, CONTENT, WRITER_NO) VALUES(SEQ_ANNOUNCEMENT_BOARD_NO.NEXTVAL , '이벤트 안내 1' , '이번 달, 저희 서비스를 이용하는 회원님들을 위한 이벤트가 준비되었습니다.' || CHR(10) || '  자세한 내용은 다음 공지를 확인해주시기 바랍니다.' || CHR(10) || '  감사합니다.', '1');
INSERT INTO ANNOUNCEMENT_BOARD(NO, TITLE, CONTENT, WRITER_NO) VALUES(SEQ_ANNOUNCEMENT_BOARD_NO.NEXTVAL , '이벤트 안내 2' , '가장 많은 리뷰를 남겨주신 세 분에게 상금이 지급될 예정입니다.' || CHR(10) || '  많은 참가 부탁드립니다.' || CHR(10) || '  감사합니다.', '1');


------------- 자유게시판 추가 -------------

INSERT INTO BOARD (NO, TITLE, CONTENT, WRITER_NO, ENROLL_DATE, DEL_YN) 
VALUES (SEQ_BOARD_NO.NEXTVAL, '최근 본 영화 추천해주세요!', '요즘 본 영화 중에 재밌었던 영화가 있나요? 추천해주세요!', 2, SYSDATE, 'N');
INSERT INTO BOARD (NO, TITLE, CONTENT, WRITER_NO, ENROLL_DATE, DEL_YN) 
VALUES (SEQ_BOARD_NO.NEXTVAL, '오늘의 일기: 행복한 하루였어요', '오늘은 친구들과 함께 좋은 시간을 보냈어요. 행복한 하루였습니다.', 3, SYSDATE, 'N');
INSERT INTO BOARD (NO, TITLE, CONTENT, WRITER_NO, ENROLL_DATE, DEL_YN) 
VALUES (SEQ_BOARD_NO.NEXTVAL, '여행 가고 싶은 곳이 어디인가요?', '여행을 계획 중인데, 여러분이 가보고 싶은 여행지가 어디인지 궁금합니다. 추천 부탁드려요!', 4, SYSDATE, 'N');
INSERT INTO BOARD (NO, TITLE, CONTENT, WRITER_NO, ENROLL_DATE, DEL_YN) 
VALUES (SEQ_BOARD_NO.NEXTVAL, '최근 읽은 책 공유해요!', '요즘 읽은 책 중에 인상 깊었던 책이 있나요? 함께 공유해주세요!', 5, SYSDATE, 'N');
INSERT INTO BOARD(NO, TITLE, CONTENT, WRITER_NO) 
VALUES(SEQ_BOARD_NO.NEXTVAL, '오늘 아침 뭐었는지 공유', '오늘 아침에 계란 42개 먹었습니다.. 맛있었네요. 조금 배부르기도 하네요', 4);
INSERT INTO BOARD(NO, TITLE, CONTENT, WRITER_NO) 
VALUES(SEQ_BOARD_NO.NEXTVAL, '저녁 뭐먹지', 'ㅋㅋ저녁 뭐먹지,, 추천점여', 3);
INSERT INTO BOARD(NO, TITLE, CONTENT, WRITER_NO) 
VALUES(SEQ_BOARD_NO.NEXTVAL, '하루에 커피 몇 잔이 좋을까요?', '커피 하루에 89잔 먹는데 괜찮은지요?', 7);
INSERT INTO BOARD(NO, TITLE, CONTENT, WRITER_NO) 
VALUES(SEQ_BOARD_NO.NEXTVAL, '컴퓨터 게임 추천', '피카츄배구 추천', 5);
INSERT INTO BOARD(NO, TITLE, CONTENT, WRITER_NO) 
VALUES (SEQ_BOARD_NO.NEXTVAL, '오늘 아침 먹은거 공유', '저는 오늘 아침에 사과 10개 먹었습니다. 아직 배고프네요.', 5);
INSERT INTO BOARD(NO, TITLE, CONTENT, WRITER_NO) 
VALUES (SEQ_BOARD_NO.NEXTVAL, '오늘의 일상', '오늘 하루를 어떻게 보냈는지 공유하고 싶습니다. 함께 공유해주세요!', 3);
INSERT INTO BOARD(NO, TITLE, CONTENT, WRITER_NO) 
VALUES (SEQ_BOARD_NO.NEXTVAL, '뽀삐', '우리집 강아지 귀엽죠? (대충 강아지 사진)', 4);
INSERT INTO BOARD(NO, TITLE, CONTENT, WRITER_NO) 
VALUES (SEQ_BOARD_NO.NEXTVAL, '너네는 이런거 하지마라...', '아는 지인이 해준 말 믿고 대출 땡겨서 코인에 전재산 넣어놨더니 xx 하루만에 절반 날아갔다.', 6);
INSERT INTO BOARD(NO, TITLE, CONTENT, WRITER_NO) 
VALUES (SEQ_BOARD_NO.NEXTVAL, '3대 500', '이걸 왜 못하나요? 1년만 운동해도 500은 가볍게 할 수 있을 것 같네요', 7);
INSERT INTO BOARD(NO, TITLE, CONTENT, WRITER_NO) 
VALUES (SEQ_BOARD_NO.NEXTVAL, '하....니넨 롤하지 마라 ', '롤하다 맨탈이 갈린다....애들 아이디 산것도 아니고 왜이리 못하냐', 3);
INSERT INTO BOARD(NO, TITLE, CONTENT, WRITER_NO) 
VALUES (SEQ_BOARD_NO.NEXTVAL, '주식 추천좀....', '주식 시작했는데 뭐사야함? 우량주사고 존버 해야하나....', 6);
INSERT INTO BOARD(NO, TITLE, CONTENT, WRITER_NO) 
VALUES (SEQ_BOARD_NO.NEXTVAL, '루틴 알려주실 헬겔러 찾습니다', '운동하는데 뭔가 잘안되는거 같은데 알려줄 형님 구합니다', 5);
INSERT INTO BOARD(NO, TITLE, CONTENT, WRITER_NO) 
VALUES (SEQ_BOARD_NO.NEXTVAL, '여친구함@@@@@@@@ 운동하는 좋아하는 여자 구함', '여친 급구 제발 소개도 받음 답글 다면 정보 드림', 4);
INSERT INTO BOARD (NO, TITLE, CONTENT, WRITER_NO, ENROLL_DATE, DEL_YN)
VALUES (SEQ_BOARD_NO.NEXTVAL, '다들 요즘 부스터 뭐드시나요', '운동 전 아아만 마시는데 부스터도 마시고싶어요 다들 뭐드시는지 추천해주세요', 7 , SYSDATE, 'N');
INSERT INTO BOARD (NO, TITLE, CONTENT, WRITER_NO, ENROLL_DATE, DEL_YN)
VALUES (SEQ_BOARD_NO.NEXTVAL, '몇분할?', '다들 몇분할 하세요? 전 어깨 가슴 하체 등 4분할 합니다', 2 , SYSDATE, 'N');
INSERT INTO BOARD (NO, TITLE, CONTENT, WRITER_NO, ENROLL_DATE, DEL_YN)
VALUES (SEQ_BOARD_NO.NEXTVAL, '하체운동 루틴', '하체운동 할 때 요즘 햄스트링 운동하려고 덤벨 스티프 데드리프트 많이하고있는데 효과 좋은 것 같아요 15-20개씩 4세트 추가해보세요~', 5 , SYSDATE, 'N');
INSERT INTO BOARD (NO, TITLE, CONTENT, WRITER_NO, ENROLL_DATE, DEL_YN)
VALUES (SEQ_BOARD_NO.NEXTVAL, '다이어트 정체기', '한달째 정체기입니다 너무 스트레스받고 그냥 먹고싶은데 여러분들은 이럴 때 어떻게 해결하세요 ㅠㅠ', 3 , SYSDATE, 'N');

------------- NORMAL 물품 추가 -------------
INSERT INTO NORMAL_PRODUCT(NORMAL_PROD_NO, NAME ,PRICE,DESCRIPTION)
VALUES (SEQ_NORMAL_PROD_NO.NEXTVAL ,'제로투히어로 카모 무릎보호대',19000,'무릎을 안정적으로 잡아주는 무릎보호대');
INSERT INTO NORMAL_PRODUCT(NORMAL_PROD_NO, NAME ,PRICE,DESCRIPTION)
VALUES (SEQ_NORMAL_PROD_NO.NEXTVAL ,'제로투히어로 하이브리드 네오프렌 팔꿈치 보호대',31900,'고중량에도 부담 없는 고정력과 압박감');
INSERT INTO NORMAL_PRODUCT(NORMAL_PROD_NO, NAME ,PRICE,DESCRIPTION)
VALUES (SEQ_NORMAL_PROD_NO.NEXTVAL ,'제로투히어로 면 손목 보호대',10900,'프로 선수들의 극찬,응집된 기술력,디자인과 기능성 모두 잡은 손목 보호대');
INSERT INTO NORMAL_PRODUCT(NORMAL_PROD_NO, NAME ,PRICE,DESCRIPTION)
VALUES (SEQ_NORMAL_PROD_NO.NEXTVAL ,'Harbinger 헬스 벨트 리프팅 웨이트 복압 허리보호대',62000,'편안한 착용감 프리웨이트에 최적화된 벨트');
INSERT INTO NORMAL_PRODUCT(NORMAL_PROD_NO, NAME ,PRICE,DESCRIPTION)
VALUES (SEQ_NORMAL_PROD_NO.NEXTVAL ,'Harbinger 에르고 핏 바 밴드',40700,'내구성 좋은 고밀도 EVA폼 소재, 등고선 설계로 무게 밸런스');
INSERT INTO NORMAL_PRODUCT(NORMAL_PROD_NO, NAME ,PRICE,DESCRIPTION)
VALUES (SEQ_NORMAL_PROD_NO.NEXTVAL ,'Harbinger 3인치 헤비 듀티 앵클 커프',26400,'전 세계 케이블 머신과 호환되는 헤비 듀티 스틸 D링 , 발목 근육 운동에 도움');
INSERT INTO NORMAL_PRODUCT(NORMAL_PROD_NO, NAME ,PRICE,DESCRIPTION)
VALUES (SEQ_NORMAL_PROD_NO.NEXTVAL ,'SHIELD 파워리프팅 헬스 스트랩',30000,'강력한 그립력,하이퀄리티AND스타일리시한 스트랩,프리미엄 위빙 테이프');
INSERT INTO NORMAL_PRODUCT(NORMAL_PROD_NO, NAME ,PRICE,DESCRIPTION)
VALUES (SEQ_NORMAL_PROD_NO.NEXTVAL ,'SHIELD 프리미엄 AB 스트랩 ',42000,'뛰어난 탄성력과 제품 복원력을 가진 프리미엄 네오프렌 소재');
INSERT INTO NORMAL_PRODUCT(NORMAL_PROD_NO, NAME ,PRICE,DESCRIPTION)
VALUES (SEQ_NORMAL_PROD_NO.NEXTVAL ,'SHIELD 웜업 파워버닝 크림',30000,'운동전 / 후 최상의 컨디션 유지에 도움 , 뭉친근육 피로를 효과적으로 풀어줌');
INSERT INTO NORMAL_PRODUCT(NORMAL_PROD_NO, NAME ,PRICE,DESCRIPTION)
VALUES (SEQ_NORMAL_PROD_NO.NEXTVAL ,'HDEX 우먼스 리브드 숄더 크롭탑',50000,'캐주얼한 무드로 연출되는 골지 디자인');
INSERT INTO NORMAL_PRODUCT(NORMAL_PROD_NO, NAME ,PRICE,DESCRIPTION)
VALUES (SEQ_NORMAL_PROD_NO.NEXTVAL ,'HDEX 우먼스 파이핑 나일론 쇼프',84000,'고밀도 원단으로 제작된 우먼스 쇼프로 가벼운 액티비티 활동');
INSERT INTO NORMAL_PRODUCT(NORMAL_PROD_NO, NAME ,PRICE,DESCRIPTION)
VALUES (SEQ_NORMAL_PROD_NO.NEXTVAL ,'HDEX 우먼스 심볼 딥 네크 크롭 숏 슬리브',61200,'가볍고 유연한 신축성으로 편안한 착용감과 피부에 자극 없는 원단');
INSERT INTO NORMAL_PRODUCT(NORMAL_PROD_NO, NAME ,PRICE,DESCRIPTION)
VALUES (SEQ_NORMAL_PROD_NO.NEXTVAL ,'MUSCLE ARMED 더플백',179000,'넓은 수납공간 용도별로 구분 사용이 가능한 7개의 포켓');
INSERT INTO NORMAL_PRODUCT(NORMAL_PROD_NO, NAME ,PRICE,DESCRIPTION)
VALUES (SEQ_NORMAL_PROD_NO.NEXTVAL ,'MUSCLE ARMED 오버핏 T-SHIRT',64500,'뒷판 어깨 절개 포인트,어깨운동에 최적화,조직감이 다른 두 종류의 메쉬 원단 사용');
INSERT INTO NORMAL_PRODUCT(NORMAL_PROD_NO, NAME ,PRICE,DESCRIPTION)
VALUES (SEQ_NORMAL_PROD_NO.NEXTVAL ,'MUSCLE ARMED 액티브 테그 와이드 PANTS',133000,'립과 나노립 원단 배색사용 나일론 원단을 사용하여 건조시간 상대적으로 짧고 가벼움');

------------- NORMAL 리뷰 추가 -------------
INSERT INTO NORMAL_REVIEW( NORMAL_REVIEW_NO,REVIEW_TITLE ,REVIEW ,NORMAL_PROD_NO,WRITER_NO)
VALUES (SEQ_NORMAL_REVIEW_NO.NEXTVAL,'제로투 히어로 무릎보호대','무릎이 너무 아파서 하나 장만했어요 디자인도 이쁘고 짱짱해서 좋아요',1,2);
INSERT INTO NORMAL_REVIEW( NORMAL_REVIEW_NO,REVIEW_TITLE ,REVIEW ,NORMAL_PROD_NO,WRITER_NO)
VALUES (SEQ_NORMAL_REVIEW_NO.NEXTVAL,'바지 추천해드림~','바지가 필요해서 하나 장만했는데 데일리로 입기 좋아요 :)',15,7);
INSERT INTO NORMAL_REVIEW( NORMAL_REVIEW_NO,REVIEW_TITLE ,REVIEW ,NORMAL_PROD_NO,WRITER_NO)
VALUES (SEQ_NORMAL_REVIEW_NO.NEXTVAL,'발열크림 후기 남겨드려요','요즘 날씨 쌀쌀해서 부상입을까봐 하나 장만했는데 몸에 열도 빠르게 올라서 안전득근 할 수 있었습니다~',9,4);
INSERT INTO NORMAL_REVIEW( NORMAL_REVIEW_NO,REVIEW_TITLE ,REVIEW ,NORMAL_PROD_NO,WRITER_NO)
VALUES (SEQ_NORMAL_REVIEW_NO.NEXTVAL,'머슬암드 티셔츠 후기','가격대가 좀 나가서 살까말까 고민했는데 통풍도 잘되서 가격값 하는구나 싶습니다 좋습니다',14,3);
INSERT INTO NORMAL_REVIEW( NORMAL_REVIEW_NO,REVIEW_TITLE ,REVIEW ,NORMAL_PROD_NO,WRITER_NO)
VALUES (SEQ_NORMAL_REVIEW_NO.NEXTVAL,'팔꿈치보호대 굳굳~~~','요즘 어깨운동이나 가슴운동 할 때 팔꿈치 할때 뚝 소리가 좀 나서 하나 장만했는데 굳굳 좋습니다 나중에 또 살게요~',2,6);
INSERT INTO NORMAL_REVIEW( NORMAL_REVIEW_NO,REVIEW_TITLE ,REVIEW ,NORMAL_PROD_NO,WRITER_NO)
VALUES (SEQ_NORMAL_REVIEW_NO.NEXTVAL,'무릎보호대','니슬리브로는 많이 사용해봤는데 랩은 처음입니다 근데 좀 불편하네요 전 슬리브가 더 좋은 것 같아요 ㅠ',1,4);
INSERT INTO NORMAL_REVIEW( NORMAL_REVIEW_NO,REVIEW_TITLE ,REVIEW ,NORMAL_PROD_NO,WRITER_NO)
VALUES (SEQ_NORMAL_REVIEW_NO.NEXTVAL,'허리보호대','다들 허리보호대 하나씩 장만하고 계시죠? 근데 저는 하빈져가 제일 좋은 것 같아요 한세트 하고나서 찍찍이 뜯는 쾌감 미쳤습니다',4,3);
INSERT INTO NORMAL_REVIEW( NORMAL_REVIEW_NO,REVIEW_TITLE ,REVIEW ,NORMAL_PROD_NO,WRITER_NO)
VALUES (SEQ_NORMAL_REVIEW_NO.NEXTVAL,'이걸 뭐라설명해야지','케이블 힙운동 할 때 많이 사용하는데 케이블이라 무게를 쉽게 올릴 수 도 있어서 너무 좋아요',6,3);
INSERT INTO NORMAL_REVIEW( NORMAL_REVIEW_NO,REVIEW_TITLE ,REVIEW ,NORMAL_PROD_NO,WRITER_NO)
VALUES (SEQ_NORMAL_REVIEW_NO.NEXTVAL,'에이치덱스','전 짐웨어 항상 에이치덱스만 애용하는 것 같아요 디자인도 이쁜데 실용성도 있어서 자주 삽니다 ',10,7);
INSERT INTO NORMAL_REVIEW( NORMAL_REVIEW_NO,REVIEW_TITLE ,REVIEW ,NORMAL_PROD_NO,WRITER_NO)
VALUES (SEQ_NORMAL_REVIEW_NO.NEXTVAL,'헬스 짐가방 추천','나이키는 너무 흔해서 다른가방 찾다가 머슬암드꺼 보게되었는데 가격대가 좀 있지만 실용성좋고 포켓이 많아서 좋은 것 같아요',13,3);
INSERT INTO NORMAL_REVIEW( NORMAL_REVIEW_NO,REVIEW_TITLE ,REVIEW ,NORMAL_PROD_NO,WRITER_NO)
VALUES (SEQ_NORMAL_REVIEW_NO.NEXTVAL,'여자 짐웨어 추천','그냥 이것저것보다가 젝시믹스보다 더 이쁜 거 없나 찾다가 에이치덱스를 처음으로 알게되었는데 이쁘고 좋네요',12,5);
INSERT INTO NORMAL_REVIEW( NORMAL_REVIEW_NO,REVIEW_TITLE ,REVIEW ,NORMAL_PROD_NO,WRITER_NO)
VALUES (SEQ_NORMAL_REVIEW_NO.NEXTVAL,'손목스트랩 추천','렉풀하는데 줄로 된 스트랩 필요했는데 짱짱하고 밀착력이 좋아서 무게 20키로나 더 올렸습니다~',7,6);
INSERT INTO NORMAL_REVIEW( NORMAL_REVIEW_NO,REVIEW_TITLE ,REVIEW ,NORMAL_PROD_NO,WRITER_NO)
VALUES (SEQ_NORMAL_REVIEW_NO.NEXTVAL,'보호대 추천합니다','아묻따 제로투히어로 제일 좋습니다 프로선수들이 사용했다고 하길래 믿고 사봤는데 역시 제투히 입니다',3,7);
INSERT INTO NORMAL_REVIEW( NORMAL_REVIEW_NO,REVIEW_TITLE ,REVIEW ,NORMAL_PROD_NO,WRITER_NO)
VALUES (SEQ_NORMAL_REVIEW_NO.NEXTVAL,'엉덩이 운동','케이블로 하는 엉덩이운동 커프 찾고있었는데 헬스장에 없어서 개인용 하나 장만했어요~',6,2);
INSERT INTO NORMAL_REVIEW( NORMAL_REVIEW_NO,REVIEW_TITLE ,REVIEW ,NORMAL_PROD_NO,WRITER_NO)
VALUES (SEQ_NORMAL_REVIEW_NO.NEXTVAL,'색도 이쁘고 만족해요','데일리로 입을겸 하나 장만했는데 나쁘지않네요 가볍고 나일론 소재라서 땀도 안차서 좋아요',15,6);

COMMIT;


